name: Test All Platforms
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-latest, macos-14]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Run Unit Tests
        run: dotnet test GDVM.Tests --configuration Release --no-build --verbosity normal --logger "console;verbosity=detailed"

      - name: Run E2E Tests (Linux only)
        if: startsWith(matrix.os, 'ubuntu')
        run: dotnet test GDVM.Tests.EndToEnd --configuration Release --no-build --verbosity normal --logger "console;verbosity=detailed"
